version: 2

jobs:
  react:
    working_directory: ~/split

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - react-{{ .Branch }}-{{ checksum "package.json" }}
            - react-{{ .Branch }}
            - react-master-{{ checksum "package.json" }}
            - react-master

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: react-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/split/node_modules

  serverless:
    working_directory: ~/split

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - serverless-{{ .Branch }}-{{ checksum "api/package.json" }}
            - serverless-{{ .Branch }}
            - serverless-master-{{ checksum "api/package.json" }}
            - serverless-master

      - run:
          name: Install dependencies
          command: cd api && yarn install

      - run:
          name: Run tests
          command: cd api && yarn test

      - save_cache:
          key: serverless-{{ .Branch }}-{{ checksum "api/package.json" }}
          paths:
            - ~/.yarn
            - ~/split/api/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - react
      - serverless
