service: split

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2
  profile: serverless
  memorySize: 256
  environment:
    CONSUMER_KEY: ${self:custom.env.consumerKey}
    SECRET_KEY: ${self:custom.env.secretKey}

custom:
  env: ${file(./env.yml)}

functions:
  authUrl:
    handler: handler.authUrl
    events:
      - http:
          path: authUrl
          method: get
  cleanTransactions:
    handler: handler.cleanTransactions
    events:
      - schedule: rate(6 hours)
    environment:
      TARGET_URL: https://us-central1-split-9c056.cloudfunctions.net/cleanTransactions
