service: split

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2
  profile: serverless
  memorySize: 256
  environment:
    CALLBACK_URL: ${self:custom.env.callbackUrl}
    CONSUMER_KEY: ${self:custom.env.consumerKey}
    SECRET_KEY: ${self:custom.env.secretKey}

custom:
  env: ${file(./env.yml)}

functions:
  requestToken:
    handler: handler.requestToken
    events:
      - http:
          path: requestToken
          method: get
          cors: true
  accessToken:
    handler: handler.accessToken
    events:
      - http:
          path: accessToken
          method: post
          cors: true
  cleanTransactions:
    handler: handler.cleanTransactions
    events:
      - schedule: rate(6 hours)
    environment:
      TARGET_URL: https://us-central1-split-9c056.cloudfunctions.net/cleanTransactions
